### ISSUE TITLE
css functionality does not work in storybook

### ISSUE THREAD

**Issue by shrivatsabhatp** [shrivatsabhat/incredible-counter#37]
**Describe the bug**
class names are not working in the storybook components; no styles applied. 

**To Reproduce**
Steps to reproduce the behaviour:

1. Run `yarn storybook`
2. Click on any components that are linked to storybook
3. Check the component, no style applied

**Expected behaviour**
Whatever style applied to the component should appear or should apply.

**Comment by shrivatsabhat** [comment]
reverted the storybook and removed from the package
